# Generated by Django 4.1.4 on 2023-01-10 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 10, 11, 45, 44, 887298)
            ),
        ),
    ]
